version: '3.8'

services:
  mysqldbb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: concesionario
      MYSQL_USER: sa
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-t:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - springboot-mysql-net
  dealer:
    depends_on:
      - mysqldbb
    image: springbootapi:latest
    expose:
      - "8080"
    ports:
      - "8008:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldbb:3306/concesionario?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "sa",
        "spring.datasource.password" : "12345678",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
      }'
    container_name: dealer
    networks:
      - springboot-mysql-net


networks:
  springboot-mysql-net:
    driver: bridge

volumes:
  mysql-data-t:

